

export enum Queries {
    DELETE = "DELETE",
    INHERIT = "INHERIT",
    INSERT = "INSERT",
    INSERT_IF_EVERY = "INSERT_IF_EVERY",
    INSERT_IF_SOME = "INSERT_IF_SOME",
    SELECT_ALL = "SELECT_ALL",
    SELECT_ONCE = "SELECT_ONCE",
    SET = "SET",
    UPDATE_ALL = "UPDATE_ALL",
    UPDATE_ONCE = "UPDATE_ONCE",
    WIPE = "WIPE",
    ABSORB = "ABSORB",

}